import numpy as np

arr = np.array([1, 2, 3, 4, 5], float)
print(arr)
print(arr[:2])
arr = np.array([[1, 2, 3], [4, 5, 6]], float)
print(arr)
print(arr[0, 0])
print(arr[0, 2])
print(arr[:3, :2])
print(arr[-1:, -2:])
print(arr.shape)
print(arr.dtype)
print(len(arr))
print(2 in arr)
print(0 in arr)
print([1, 2, 3] in arr)
arr = np.array(range(10), float)
print(arr)
arr = arr.reshape((5, 2))
arr = arr.reshape(5, 2)
print(arr)
print(arr.shape)
a = np.array([1, 2, 3], float)
b = a
c = a.copy()
a[0] = 0
print(a, b, c)
a = a.fill(0)
print(a, b, c)
a = np.array(range(6), float).reshape(2, 3)
print(a)
print(a.transpose())
a.flatten()
print(a)
print(a.flatten())
a = np.array([1, 2, 3], float)
b = np.array([5, 6, 7], float)
c = np.array([8, 9, 10], float)
print(np.concatenate((a, b, c)))
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7, 8]], float)
print(np.concatenate((a, b)))
print(np.concatenate((a, b), axis=0))
print(np.concatenate((a, b), axis=1))
a = np.array([1, 2, 3, 4, 5], float)
a = a[:, np.newaxis]
print(a)
a = np.array([1, 2, 3, 4, 5], float)
a = a[np.newaxis, :]
print(a)
a = np.arange(5, dtype=float)
print(a)
a = np.arange(1, 6, 2, dtype=float)
print(a)
a = np.ones((2, 3), float)
print(a)
a = np.ones(7, float)
print(a)
a = np.zeros((2, 3), float)
print(a)
a = np.zeros(7, float)
print(a)
b = np.zeros_like(a)
print(b)
b = np.ones_like(a)
print(b)
a = np.identity(4, dtype=int)
print(a)
a = np.eye(4, k=1, dtype=float)
print(a)
a = np.array([1, 2, 3], float)
b = np.array([5, 6, 7], float)
print('----------------')
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a % b)
print(a**b)
a = np.array([[1, 2], [3, 4], [5, 6]], dtype=int)
b = np.array([-1, 3], dtype=int)
print(a+b)
b = np.array([[1, 2], [3, 4], [5, 6]], dtype=int)
a = np.array([-1, 3], dtype=int)
print(a+b)
a = np.zeros((2, 2), dtype=int)
b = np.array([-1, 3], dtype=float)
print(a+b)
a = np.array([1, 4, 9])
print(np.sqrt(a))
a = np.array([1.3, 4.5, 9.1])
print(np.floor(a))
print(np.ceil(a))
print(np.trunc(a))
print(np.rint(a))
print(np.round(a))
print(np.pi)
print(np.e)
for x in a:
    print(x)
c = np.array([[1, 2, 7], [3, 4, 8], [5, 6, 9]])
for i, j, x in c:
    print(i, j, x)
for i in c:
    for j in i:
        print(j)

print(sorted(a))
a.sort()
print(a)
a = np.array([6, 2, 5, -1, 0, 0], float)
a = a.clip(0, 5)
print(a)
a = np.unique(a)
a = np.array([[1, 2], [3, 4]])
print(a.diagonal())
a = np.array([[0, 2], [3, 4]], float)
b = np.array([[5, 6], [7, 8]], float)
print(a > b)
print(a == b)
print(a <= b)
c = np.array([True, False, True])
print(any(c))
print(all(c))
print(np.logical_and(a > 2, b < 3))
print(np.logical_or(a > 2, b < 3))
print(np.logical_not(a > 2))
a = np.where(a != 0, 1/a, a)
print(a)
a = np.where(a > 0, 3, 2)
print(a)
a = np.array([[0, 1], [3, 0]])
a = a.nonzero()
print(a)
a = np.array([[0, np.nan], [3, np.inf]])
print(a)
print(np.isfinite(a))
print(np.isnan(a))
print(a[a>0])
